Veterinaria/Controllers/razaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
    public class razaController : Controller
    {
        private veterinariaEntities db = new veterinariaEntities();

        // GET: raza
        public ActionResult Index()
        {
            return View(db.tbl_raza.ToList());
        }

        // GET: raza/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_raza tbl_raza = db.tbl_raza.Find(id);
            if (tbl_raza == null)
            {
                return HttpNotFound();
            }
            return View(tbl_raza);
        }

        // GET: raza/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: raza/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_r,nombre_r")] tbl_raza tbl_raza)
        {
            if (ModelState.IsValid)
            {
                db.tbl_raza.Add(tbl_raza);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_raza);
        }

        // GET: raza/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_raza tbl_raza = db.tbl_raza.Find(id);
            if (tbl_raza == null)
            {
                return HttpNotFound();
            }
            return View(tbl_raza);
        }

        // POST: raza/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_r,nombre_r")] tbl_raza tbl_raza)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_raza).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_raza);
        }

        // GET: raza/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_raza tbl_raza = db.tbl_raza.Find(id);
            if (tbl_raza == null)
            {
                return HttpNotFound();
            }
            return View(tbl_raza);
        }

        // POST: raza/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tbl_raza tbl_raza = db.tbl_raza.Find(id);
            db.tbl_raza.Remove(tbl_raza);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Veterinaria/Views/raza/Create.cshtml
@model Veterinaria.Models.tbl_raza

@{
    ViewBag.Title = "Create";
}
    <h2>Registrar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Raza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="col-form-label col-md-2">ID</label>
        @*@Html.LabelFor(model => model.id_r, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_r, new { htmlAttributes = new { @class = "form-control", @autocomplete="off" } })
            @Html.ValidationMessageFor(model => model.id_r, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="col-form-label col-md-2">Nombre</label>
        @*@Html.LabelFor(model => model.nombre_r, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre_r, new { htmlAttributes = new { @autocomplete = "off", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre_r, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-sm btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index", "raza",new { area = "" }, new { @class = "btn btn-sm btn-secondary" })
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Veterinaria/Views/raza/Delete.cshtml
@model Veterinaria.Models.tbl_raza

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Está seguro de que desea eliminar este elemento?</h3>
<div>
    <h4>Raza</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
                   Nombre
            @*@Html.DisplayNameFor(model => model.nombre_r)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_r)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-sm btn-danger" /> |
            @Html.ActionLink("Volver a la lista", "Index", new { area = "" }, new { @class = "btn btn-sm btn-secondary btn-sm" })
        </div>
    }
</div>

Veterinaria/Views/raza/Details.cshtml
@model Veterinaria.Models.tbl_raza

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Raza</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre
            @*@Html.DisplayNameFor(model => model.nombre_r)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_r)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Actualizar", "Edit", new { id = Model.id_r }, new { @class = "btn btn-sm btn-success" }) |
    @Html.ActionLink("Volver a la lista", "Index", "raza",new { area = "" }, new { @class = "btn btn-sm btn-secondary" })
</p>

Veterinaria/Views/raza/Edit.cshtml
@model Veterinaria.Models.tbl_raza

@{
    ViewBag.Title = "Edit";
}

<h2>Actualizar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Raza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_r)

        <div class="form-group">
            Nombre
            @*@Html.LabelFor(model => model.nombre_r, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_r, new { htmlAttributes = new { @class = "form-control", @autocomplete="off" } })
                @Html.ValidationMessageFor(model => model.nombre_r, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-sm btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index",new { area = "" }, new { @class = "btn btn-sm btn-secondary" })
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Veterinaria/Views/raza/Index.cshtml
@model IEnumerable<Veterinaria.Models.tbl_raza>

@{
    ViewBag.Title = "Raza";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Registrar nueva raza", "Create", new { area = "" }, new { @class = "btn btn-sm btn-primary" })
</p>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre_r)
                </td>
                <td>
                    @Html.ActionLink("Actualizar", "Edit", new { id = item.id_r }, new { @class = "badge badge-success" }) |
                    @Html.ActionLink("Detalles", "Details", new { id = item.id_r }, new { @class = "badge badge-info" }) |
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.id_r }, new { @class = "badge badge-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>